identifiers {
  type: NAME
  value: "placeholder"
}
inputs {
  key: "base"
  value {
    components {
      identifiers {
        type: SMILES
        value: "placeholder"
      }
      identifiers {
        type: NAME
        value: "placeholder"
      }
      moles {
        value: 200.0
        units: NANOMOLE
      }
      reaction_role: REAGENT
      is_limiting: false
    }
    components {
      identifiers {
        type: SMILES
        value: "CS(C)=O"
      }
      identifiers {
        type: NAME
        value: "DMSO"
      }
      volume {
        value: 0.25
        units: MICROLITER
      }
      reaction_role: SOLVENT
      is_limiting: false
      volume_includes_solutes: true
    }
    addition_order: 1
  }
}
inputs {
  key: "catalyst"
  value {
    components {
      identifiers {
        type: SMILES
        value: "placeholder"
      }
      identifiers {
        type: NAME
        value: "placeholder"
      }
      moles {
        value: 10.0
        units: NANOMOLE
      }
      reaction_role: REAGENT
      is_limiting: false
    }
    components {
      identifiers {
        type: SMILES
        value: "CS(C)=O"
      }
      identifiers {
        type: NAME
        value: "DMSO"
      }
      volume {
        value: 0.25
        units: MICROLITER
      }
      reaction_role: SOLVENT
      is_limiting: false
      volume_includes_solutes: true
    }
    addition_order: 1
  }
}
inputs {
  key: "reactant_1"
  value {
    components {
      identifiers {
        type: SMILES
        value: "placeholder"
      }
      identifiers {
        type: NAME
        value: "placeholder"
      }
      moles {
        value: 100.0
        units: NANOMOLE
      }
      reaction_role: REACTANT
      is_limiting: true
    }
    components {
      identifiers {
        type: SMILES
        value: "CS(C)=O"
      }
      identifiers {
        type: NAME
        value: "DMSO"
      }
      volume {
        value: 0.25
        units: MICROLITER
      }
      reaction_role: SOLVENT
      is_limiting: false
      volume_includes_solutes: true
    }
    addition_order: 1
  }
}
inputs {
  key: "reactant_2"
  value {
    components {
      identifiers {
        type: SMILES
        value: "placeholder"
      }
      identifiers {
        type: NAME
        value: "placeholder"
      }
      moles {
        value: 150.0
        units: NANOMOLE
      }
      reaction_role: REACTANT
      is_limiting: false
    }
    components {
      identifiers {
        type: SMILES
        value: "CS(C)=O"
      }
      identifiers {
        type: NAME
        value: "DMSO"
      }
      volume {
        value: 0.25
        units: MICROLITER
      }
      reaction_role: SOLVENT
      is_limiting: false
      volume_includes_solutes: true
    }
    addition_order: 1
  }
}
setup {
  vessel {
    type {
      type: WELL_PLATE
      details: "Corning EchoTM qualified, Cat. No. 3730"
    }
    material {
      type: PLASTIC
      details: "Cyclic Olefin-Copolymer"
    }
    attachments {
      type: CAP
      details: "perfluoroalkoxy alkane (PFA) mat (Analytical-Sales, Cat. No. 96981)"
    }
    attachments {
      type: CAP
      details: "silicon rubber mat (Analytical-Sales, Cat. No. 96982)"
    }
    attachments {
      type: CUSTOM
      details: "clamp (Arctic White, Cat. No. AWSC-051001)"
    }
    volume {
      value: 12.5
      units: MICROLITER
    }
  }
  is_automated: true
  automation_platform: "Mosquito(R) HTS liquid handling robot; TTP Labtech native software; Free-Slate Library Studio"
  environment {
    type: GLOVE_BOX
    details: "MBraun glovebox operating with a constant N2-purge (oxygen typically <5 ppm)"
  }
}
conditions {
  temperature {
    control {
      type: AMBIENT
      details: "The plate was then allowed to sit at room temperature for 22 hours"
    }
  }
  pressure {
    control {
      type: SEALED
      details: "The 1536-well plates were covered by a perfluoroalkoxy alkane (PFA) mat (Analytical-Sales, Cat. No. 96981), followed by a silicon rubber mat (Analytical- Sales, Cat. No. 96982) and then secured with a clamp (Arctic White, Cat. No. AWSC-051001)"
    }
    atmosphere {
      type: NITROGEN
    }
  }
  stirring {
    method {
      type: NONE
    }
  }
}
notes {
  is_heterogeneous: false
  is_sensitive_to_moisture: true
  is_sensitive_to_oxygen: true
  procedure_details: "The Mosquito was used to combine the source plate solutions by multi-aspiration of 250 nL of each of the four reaction components and then to dose the resulting reaction mixture (1 uL) into a 1536-well plate"
}
observations {
  time {
    value: 0.0
    units: HOUR
  }
  comment: "fully dosed 1536 reaction well plate"
  image {
    url: "https://postimg.cc/fk783Pbw"
    description: "fully dosed plate"
    format: "png"
  }
}
observations {
  time {
    value: 0.0
    units: HOUR
  }
  comment: "clamped 1536-wp - perspective view"
  image {
    url: "https://postimg.cc/YjBXC7Mn"
    description: "sealed plate"
    format: "png"
  }
}
workup {
  type: ADDITION
  input {
    components {
      identifiers {
        type: SMILES
        value: "CC(=O)O"
      }
      identifiers {
        type: NAME
        value: "acetic acid"
      }
      volume {
        value: 0.15
        units: MICROLITER
      }
      reaction_role: WORKUP
      is_limiting: false
    }
    components {
      identifiers {
        type: SMILES
        value: "c1ccc(-c2ccccc2)cc1"
      }
      identifiers {
        type: NAME
        value: "biphenyl"
      }
      moles {
        value: 3.0
        units: NANOMOLE
      }
      reaction_role: INTERNAL_STANDARD
      is_limiting: false
    }
    components {
      identifiers {
        type: SMILES
        value: "CS(C)=O"
      }
      identifiers {
        type: NAME
        value: "DMSO"
      }
      volume {
        value: 2.85
        units: MICROLITER
      }
      reaction_role: WORKUP
      is_limiting: false
    }
  }
  stirring {
    method {
      type: AGITATION
      details: "The Mosquito mixing feature was used three times"
    }
  }
  is_automated: true
}
workup {
  type: ADDITION
  input {
    components {
      identifiers {
        type: SMILES
        value: "CS(C)=O"
      }
      identifiers {
        type: NAME
        value: "DMSO"
      }
      volume {
        value: 75.0
        units: MICROLITER
      }
      reaction_role: WORKUP
      is_limiting: false
    }
  }
  stirring {
    method {
      type: AGITATION
      details: "The Mosquito mixing feature was used three times"
    }
  }
  is_automated: true
}
outcomes {
  reaction_time {
    value: 22.0
    units: HOUR
  }
  products {
    compound {
      identifiers {
        type: SMILES
        value: "placeholder"
      }
    }
    is_desired_product: true
    analysis_identity: "UPLC"
    analysis_yield: "UPLC"
  }
  products {
    compound {
      identifiers {
        type: SMILES
        value: "placeholder"
      }
    }
    is_desired_product: false
    analysis_identity: "UPLC"
    analysis_yield: "UPLC"
  }
  products {
    compound {
      identifiers {
        type: SMILES
        value: "placeholder"
      }
    }
    is_desired_product: false
    analysis_identity: "UPLC"
    analysis_yield: "UPLC"
  }
  analyses {
    key: "UPLC"
    value {
      type: LC
      details: "Column: Acquity UPLC BEH C18 1.7um 2.1x50mm (Part # 186002350), pH 3.5 Stock Solution: 12.6g ammonium formate + 7.9ml formic acid to 1L water, Mobile Phase A: 40ml pH 3.5 stock solution + 3960ml Water, Mobile Phase B: 40ml pH 3.5 stock solution + 360ml Water + 3600ml ACN, Strong Wash: 300ml IPA + 693ml ACN + 7ml pH 3.5 stock solution, Weak Wash: 99ml ACN + 891ml Water + 10ml pH 3.5 stock solution. The instrument was equipped with an SQD detector with electrospray ionization (ESI) source in the positive mode. High throughput data analysis to produce Excel spreadsheets was done with Virscidian Analytical StudioTM software."
      processed_data {
        key: "electrophile LC area count"
        value {
          float_value: 0.0
        }
      }
      processed_data {
        key: "internal_standard LC area count"
        value {
          float_value: 0.0
        }
      }
      processed_data {
        key: "nucleophile LC area count"
        value {
          float_value: 0.0
        }
      }
      processed_data {
        key: "product LC area count"
        value {
          float_value: 0.0
        }
      }
      instrument_manufacturer: "Waters"
      uses_internal_standard: true
    }
  }
}
provenance {
  city: "Rahway, NJ"
  doi: "10.1126/science.1259203"
  publication_url: "https://science.sciencemag.org/content/347/6217/49"
  record_created {
    time {
      value: "10/14/2020, 16:12:26"
    }
    person {
      name: "Michael R. Maser"
      orcid: "0000-0001-7895-7804"
      organization: "Caltech"
      email: "mmaser@caltech.edu"
    }
  }
}
