reactions {
  inputs {
    value {
      addition_time {
      }
      addition_speed {
      }
      addition_duration {
      }
      flow_rate {
      }
      addition_device {
      }
    }
  }
  setup {
    vessel {
      type {
      }
      material {
      }
      volume {
      }
    }
    environment {
    }
  }
  conditions {
    temperature {
      control {
      }
      setpoint {
      }
    }
    pressure {
      control {
      }
      setpoint {
      }
      atmosphere {
      }
    }
    stirring {
      method {
      }
      rate {
      }
    }
    illumination {
      type {
      }
      peak_wavelength {
      }
      distance_to_vessel {
      }
    }
    electrochemistry {
      electrochemistry_type {
      }
      current {
      }
      voltage {
      }
      electrode_separation {
      }
      cell {
      }
    }
    flow {
      flow_type {
      }
      tubing {
        diameter {
        }
      }
    }
  }
  notes {
  }
  provenance {
    experimenter {
    }
    experiment_start {
    }
    record_created {
      time {
      }
      person {
      }
    }
  }
}
