reactions {
  setup {
    vessel {
      type {
      }
      material {
      }
      volume {
        value: 0.0
        precision: 0.0
      }
    }
    is_automated: false
    environment {
    }
  }
  conditions {
    temperature {
      control {
      }
      setpoint {
        value: 0.0
        precision: 0.0
      }
    }
    pressure {
      control {
      }
      setpoint {
        value: 0.0
        precision: 0.0
      }
      atmosphere {
      }
    }
    stirring {
      method {
      }
      rate {
      }
    }
    illumination {
      type {
      }
      peak_wavelength {
        value: 0.0
        precision: 0.0
      }
      distance_to_vessel {
        value: 0.0
        precision: 0.0
      }
    }
    electrochemistry {
      electrochemistry_type {
      }
      current {
        value: 0.0
        precision: 0.0
      }
      voltage {
        value: 0.0
        precision: 0.0
      }
      electrode_separation {
        value: 0.0
        precision: 0.0
      }
      cell {
      }
    }
    flow {
      flow_type {
      }
      tubing {
        diameter {
          value: 0.0
          precision: 0.0
        }
      }
    }
    reflux: false
    pH: 0.0
    conditions_are_dynamic: false
  }
  notes {
    is_heterogeneous: false
    forms_precipitate: false
    is_exothermic: false
    offgasses: false
    is_sensitive_to_moisture: false
    is_sensitive_to_oxygen: false
    is_sensitive_to_light: false
  }
  provenance {
    experimenter {
    }
    experiment_start {
    }
    record_created {
      time {
      }
      person {
      }
    }
  }
}
