name: CI

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  run_tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up protoc
      uses: arduino/setup-protoc@v1.1.0
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install
      run: |
        cd "${GITHUB_WORKSPACE}"
        python setup.py build_py
        python setup.py install
    - name: Run pylint
      run: |
        python -m pip install --upgrade pip pylint
        pylint ord_schema
        
